#!/usr/bin/perl

use strict;
use warnings;
use CGI;
use POSIX qw(strftime);

my $q = new CGI;
my $date = strftime "%Y%m%d", localtime;

print $q->header( -charset => 'utf-8');
print $q->start_html('Dilbert');

my $count = 0;
while ($count < 30) {
    $date = strftime "%Y%m%d", localtime(time() - 24*60*60*$count);
    print $q->p("<img src=\"http://tjanster.idg.se/dilbertimages/dil$date.gif\" alt=\"dibert.gif\"/>") . "\n";
    $count++;
}

print $q->end_html;
