#!/usr/bin/perl

use strict;
use warnings;
use POSIX qw(strftime);

my $date = strftime "%Y%m%d", localtime;

print "Content-type: text/html\n\n";

print <<ENDHTML;
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Dilbert</title>
</head>
<body>
ENDHTML

my $count;
while ($count < 30) {
    $date = strftime "%Y%m%d", localtime(time() - 24*60*60*$count);
    print "<img src=\"http://tjanster.idg.se/dilbertimages/dil$date.gif\" alt=\"dibert.gif\"/>";
    print "<br />";
    $count++;
}

print <<ENDHTML;
    <!-- Yes, I'm tracking you.. ;) -->
    <script src="//static.getclicky.com/js" type="text/javascript"></script>
    <script type="text/javascript">try{ clicky.init(100686818); }catch(e){}</script>
    <noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100686818ns.gif" /></p></noscript>
</body>
</html>

ENDHTML
