#!/usr/bin/perl

use strict;
use warnings;
use POSIX qw(strftime);

my $date = strftime "%Y%m%d", localtime;

print "Content-type: text/html\n\n";

print <<ENDHTML;
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Dilbert</title>
</head>
<body>
    <img src="http://tjanster.idg.se/dilbertimages/dil$date.gif" alt="dilbert.gif"/>
</body>
</html>
ENDHTML
